# Generated by Django 3.2.3 on 2021-05-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.AddField(
            model_name='memecontestpost',
            name='contest_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.memecontest'),
            preserve_default=False,
        ),
    ]
