# Generated by Django 3.2.3 on 2021-05-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210521_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memecontestpost',
            old_name='twitter_post',
            new_name='tweet_url',
        ),
        migrations.RemoveField(
            model_name='memecontest',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='memecontest',
            name='start_date',
            field=models.DateTimeField(
                default='1970-01-01', verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
