# Generated by Django 3.2.3 on 2021-05-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210521_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecontest',
            name='prize_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memecontest',
            name='prize_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memecontest',
            name='prize_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memecontest',
            name='rules',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
