# Generated by Django 3.2.3 on 2021-05-24 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210521_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecontest',
            name='posts_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memecontestpost',
            name='wallet_address',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RetweetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100)),
                ('twitter_id', models.CharField(max_length=100)),
                ('tweet_url', models.CharField(max_length=1000)),
                ('wallet_address', models.CharField(max_length=1000, unique=True)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.memecontest')),
            ],
        ),
    ]
