# Generated by Django 3.2.3 on 2021-05-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210524_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecontest',
            name='contest_type',
            field=models.CharField(choices=[('contest', 'contest'), ('retweet', 'retweet')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
